--- #YAML:1.0
name: Rose-DBx-Object-Builder
version: 0.04
author:
  - Xufeng (Danny) Liang <danny.glue@gmail.com>
abstract: Database Table Schema Generation for Rose::DB::Object
license: perl
requires:
  Test::More: 0
  Lingua::EN::Inflect: 0
  Regexp::Common: 0
  DBI: 0
  Rose::Object: 0
  Exporter: 5.57

